# Generated by Django 4.2.4 on 2023-08-17 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_myclass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Myclass',
        ),
    ]
